//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiprolimarDB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente_TipoTelefono
    {
        public int cliente { get; set; }
        public int tipoTelefono { get; set; }
        public string numero { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual TipoTelefono TipoTelefono1 { get; set; }
    }
}
