//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiprolimarDB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Cliente_TipoTelefono = new HashSet<Cliente_TipoTelefono>();
            this.Factura = new HashSet<Factura>();
        }
    
        public int idCliente { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string correo { get; set; }
        public string nombreEmpresa { get; set; }
    
        public virtual ICollection<Cliente_TipoTelefono> Cliente_TipoTelefono { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
