//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiprolimarDB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaFactura
    {
        public int producto { get; set; }
        public int factura { get; set; }
        public int cantidad { get; set; }
    
        public virtual Factura Factura1 { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}
