//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiprolimarDB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTelefono
    {
        public TipoTelefono()
        {
            this.Cliente_TipoTelefono = new HashSet<Cliente_TipoTelefono>();
        }
    
        public int idTipoTelefono { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Cliente_TipoTelefono> Cliente_TipoTelefono { get; set; }
    }
}
