//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiprolimarDB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Rol1 = new HashSet<Rol>();
        }
    
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string contrasenna { get; set; }
        public int rol { get; set; }
    
        public virtual ICollection<Rol> Rol1 { get; set; }
    }
}
